SELECT	
		client_name
		,ASSET_TYPE_CODE 'aset tipe'
		,LEASE_ROUND_AMOUNT
		,MONTHLY_RENTAL_ROUNDED_AMOUNT 'harga sewa'
		,FA_REFF_NO_01 'plat no'
		,HANDOVER_BAST_DATE 'start date'
		,MATURITY_DATE 'end date'
		--SUM(MONTHLY_RENTAL_ROUNDED_AMOUNT)
FROM	dbo.AGREEMENT_ASSET
JOIN	dbo.AGREEMENT_MAIN ON AGREEMENT_MAIN.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
JOIN	dbo.AGREEMENT_INFORMATION ON AGREEMENT_INFORMATION.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
WHERE CLIENT_NAME like '%SURYAPATIH JAYA KREASI%'
