DECLARE @1 NVARCHAR(50) = '2008.OPLAA.2501.000090'

SELECT 'ASSET_VEHICLE',PLAT_NO,* FROM IFINAMS.dbo.ASSET_VEHICLE WHERE PLAT_NO in ('BM8079QE', 'BM8257QE')

SELECT MODEL_CODE, TYPE_ITEM_CODE, COLOUR,  FROM IFINAMS.dbo.ASSET_VEHICLE WHERE PLAT_NO in ('BM8079QE', 'BM8257QE')

SELECT 'HANDOVER_REQUEST',* 
FROM IFINAMS.dbo.HANDOVER_REQUEST WHERE ASSET_NO = @1

SELECT 'APPLICATION_ASSET',FA_CODE,FA_REFF_NO_01,FA_REFF_NO_02,FA_REFF_NO_03,* 
FROM IFINOPL.dbo.APPLICATION_ASSET WHERE ASSET_NO = @1

SELECT 'APPLICATION_ASSET_VEHICLE',* 
FROM IFINOPL.dbo.APPLICATION_ASSET_VEHICLE WHERE ASSET_NO = @1

SELECT 'OPL_INTERFACE_PURCHASE_REQUEST',FA_REFF_NO_01,FA_REFF_NO_02,FA_REFF_NO_03,FA_REFF_NO_04,FA_REFF_NO_05,FA_REFF_NO_06,MOBILIZATION_FA_CODE,* 
FROM IFINOPL.dbo.OPL_INTERFACE_PURCHASE_REQUEST where CODE = '2008.OPLPUR.2502.000005'

SELECT 'PROC_INTERFACE_PURCHASE_REQUEST',FA_REFF_NO_01,FA_REFF_NO_02,FA_REFF_NO_03,FA_REFF_NO_04,FA_REFF_NO_05,FA_REFF_NO_06,MOBILIZATION_FA_CODE,* 
FROM IFINPROC.dbo.PROC_INTERFACE_PURCHASE_REQUEST where CODE = '2008.OPLPUR.2502.000005'
    
SELECT 'PROCUREMENT_REQUEST',* 
FROM IFINPROC.dbo.PROCUREMENT_REQUEST where CODE = 'DSF.PRR.2502.000020' --gaperlu diedit

SELECT 'PROCUREMENT_REQUEST_ITEM',* 
FROM IFINPROC.dbo.PROCUREMENT_REQUEST_ITEM where PROCUREMENT_REQUEST_CODE = 'DSF.PRR.2502.000020' --edit specification, fa_code

SELECT 'PROCUREMENT',* 
FROM IFINPROC.dbo.PROCUREMENT where CODE = 'DSF.PRC.2502.000007' --edit specification



--SELECT 'APPLICATION_ASSET',FA_REFF_NO_01,ASSET_CONDITION,* 
--FROM dbo.APPLICATION_ASSET where FA_REFF_NO_01 in ('BM8079QE', 'BM8257QE')




