BEGIN TRANSACTION 
DECLARE  @1 NVARCHAR(50) = REPLACE('0002586/4/10/07/2024','/','.')
		,@2 NVARCHAR(50) = REPLACE('0003919/4/10/02/2025','/','.')
SELECT	AGREEMENT_ASSET.AGREEMENT_NO,AGREEMENT_ASSET.ASSET_NO,FIRST_PAYMENT_TYPE,BILLING_TYPE,HANDOVER_BAST_DATE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,dbo.AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO,INVOICE_STATUS,MATURITY_DATE
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.AGREEMENT_NO = AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO
JOIN	dbo.AGREEMENT_INFORMATION ON AGREEMENT_INFORMATION.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
LEFT JOIN	dbo.INVOICE ON INVOICE.INVOICE_NO = AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO
WHERE	AGREEMENT_ASSET.AGREEMENT_NO = @2

UPDATE dbo.AGREEMENT_ASSET_AMORTIZATION SET BILLING_DATE = '2025-03-28' ,MOD_BY = 'MTN-FAUZAN' ,MOD_DATE = GETDATE() ,MOD_IP_ADDRESS = 'IMON-2504000048' WHERE AGREEMENT_NO = @2

SELECT	AGREEMENT_ASSET.AGREEMENT_NO,AGREEMENT_ASSET.ASSET_NO,FIRST_PAYMENT_TYPE,BILLING_TYPE,HANDOVER_BAST_DATE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,dbo.AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO,INVOICE_STATUS,MATURITY_DATE
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.AGREEMENT_NO = AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO
JOIN	dbo.AGREEMENT_INFORMATION ON AGREEMENT_INFORMATION.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
LEFT JOIN	dbo.INVOICE ON INVOICE.INVOICE_NO = AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO
WHERE	AGREEMENT_ASSET.AGREEMENT_NO = @2

			insert into dbo.MTN_DATA_DSF_LOG
			(
				MAINTENANCE_NAME
				,REMARK
				,TABEL_UTAMA
				,REFF_1
				,REFF_2
				,REFF_3
				,CRE_DATE
				,CRE_BY
			)
			values
			(	'MTN Imon 2504000048' -- MAINTENANCE_NAME - nvarchar(50)
				,'Mohon merevisi billing date untuk kontrak No. 0003919/4/10/02/2025 (application No. 0004184/4/10/02/2025)'		-- REMARK - nvarchar(4000)
				,'MATURITY'							-- TABEL_UTAMA - nvarchar(50)
				,'0003919/4/10/02/2025'						-- REFF_1 - nvarchar(50)
				,null								-- REFF_2 - nvarchar(50)
				,null								-- REFF_3 - nvarchar(50)
				,GETDATE()							-- CRE_DATE - datetime
				,'MTNFFAUZAN'							-- CRE_BY - nvarchar(250)
				)
ROLLBACK TRANSACTION 