SELECT 
		 DEPOSIT_CODE 'no deposit'
		,CLIENT_NAME
		,depo.AGREEMENT_NO 'no agreement'
		,ALLOCATION_ORIG_AMOUNT 'amount'
		,CASE WHEN SOURCE_REFF_NAME in ('CASHIER','REVERSAL CASHIER') THEN cht.CASHIER_REMARKS
		WHEN SOURCE_REFF_NAME = 'SUSPEND ALLOCATION' THEN spa.ALLOCATIONT_REMARKS
		WHEN SOURCE_REFF_NAME = 'SUSPEND RELEASE' THEN slr.RELEASE_REMARKS
		WHEN SOURCE_REFF_NAME in ('DEPOSIT ALLOCATION', 'REVERSAL DEPOSIT ALLOCATION') THEN dan.ALLOCATIONT_REMARKS
		WHEN SOURCE_REFF_NAME = 'DEPOSIT MOVE' THEN dmv.MOVE_REMARKS
		WHEN SOURCE_REFF_NAME = 'DEPOSIT RELEASE' THEN drl.RELEASE_REMARKS
		END 'remark'
		,ALLOCATION_VALUE_DATE 'value date'
		,ALLOCATION_TRX_DATE 'transaction date'
FROM	dbo.FIN_INTERFACE_AGREEMENT_DEPOSIT_HISTORY depo
JOIN	dbo.AGREEMENT_MAIN ON AGREEMENT_MAIN.AGREEMENT_NO = depo.AGREEMENT_NO
OUTER APPLY( 
SELECT	CASHIER_REMARKS
FROM	dbo.CASHIER_TRANSACTION		
WHERE	CODE = depo.SOURCE_REFF_CODE AND depo.SOURCE_REFF_NAME in ('CASHIER','REVERSAL CASHIER')
) cht
OUTER APPLY( 
SELECT	ALLOCATIONT_REMARKS
FROM	dbo.SUSPEND_ALLOCATION		
WHERE	CODE = depo.SOURCE_REFF_CODE AND depo.SOURCE_REFF_NAME = 'SUSPEND ALLOCATION'
) spa
OUTER APPLY( 
SELECT	RELEASE_REMARKS
FROM	dbo.SUSPEND_RELEASE			
WHERE	CODE = depo.SOURCE_REFF_CODE AND depo.SOURCE_REFF_NAME = 'SUSPEND RELEASE'
) slr
OUTER APPLY( 
SELECT	ALLOCATIONT_REMARKS,DEPOSIT_CODE,ALLOCATION_ORIG_AMOUNT,ALLOCATION_VALUE_DATE,ALLOCATION_TRX_DATE
FROM	dbo.DEPOSIT_ALLOCATION		
WHERE	CODE = depo.SOURCE_REFF_CODE AND depo.SOURCE_REFF_NAME in ('DEPOSIT ALLOCATION', 'REVERSAL DEPOSIT ALLOCATION')
) dan
OUTER APPLY( 
SELECT	MOVE_REMARKS
FROM	dbo.DEPOSIT_MOVE			
WHERE	CODE = depo.SOURCE_REFF_CODE AND depo.SOURCE_REFF_NAME = 'DEPOSIT MOVE'
) dmv
OUTER APPLY( 
SELECT	RELEASE_REMARKS
FROM	dbo.DEPOSIT_RELEASE			
WHERE	CODE = depo.SOURCE_REFF_CODE AND depo.SOURCE_REFF_NAME = 'DEPOSIT RELEASE'
) drl




SELECT 
		 code 'no deposit'
		,CLIENT_NAME
		,susp.AGREEMENT_NO 'no agreement'
		,dan.ALLOCATION_ORIG_AMOUNT 'amount'
		,CASE WHEN SOURCE_REFF_NAME in ('CASHIER','REVERSAL CASHIER') THEN cht.CASHIER_REMARKS
		WHEN SOURCE_REFF_NAME = 'SUSPEND ALLOCATION' THEN spa.ALLOCATIONT_REMARKS
		WHEN SOURCE_REFF_NAME = 'SUSPEND RELEASE' THEN slr.RELEASE_REMARKS
		WHEN SOURCE_REFF_NAME in ('DEPOSIT ALLOCATION', 'REVERSAL DEPOSIT ALLOCATION') THEN dan.ALLOCATIONT_REMARKS
		WHEN SOURCE_REFF_NAME = 'DEPOSIT MOVE' THEN dmv.MOVE_REMARKS
		WHEN SOURCE_REFF_NAME = 'DEPOSIT RELEASE' THEN drl.RELEASE_REMARKS
		END 'remark'
		,dan.ALLOCATION_VALUE_DATE 'value date'
		,dan.ALLOCATION_TRX_DATE 'transaction date' 
FROM	dbo.SUSPEND_HISTORY susp
JOIN	dbo.AGREEMENT_MAIN ON AGREEMENT_MAIN.AGREEMENT_NO = susp.AGREEMENT_NO

OUTER APPLY( 
SELECT	CASHIER_REMARKS
FROM	dbo.CASHIER_TRANSACTION		
WHERE	CODE = susp.SOURCE_REFF_CODE AND susp.SOURCE_REFF_NAME in ('CASHIER','REVERSAL CASHIER')
) cht
OUTER APPLY( 
SELECT	ALLOCATIONT_REMARKS,CODE,ALLOCATION_ORIG_AMOUNT,ALLOCATION_VALUE_DATE,ALLOCATION_TRX_DATE
FROM	dbo.SUSPEND_ALLOCATION		
WHERE	CODE = susp.SOURCE_REFF_CODE AND susp.SOURCE_REFF_NAME = 'SUSPEND ALLOCATION'
) spa
OUTER APPLY( 
SELECT	RELEASE_REMARKS
FROM	dbo.SUSPEND_RELEASE			
WHERE	CODE = susp.SOURCE_REFF_CODE AND susp.SOURCE_REFF_NAME = 'SUSPEND RELEASE'
) slr
OUTER APPLY( 
SELECT	ALLOCATIONT_REMARKS,DEPOSIT_CODE,ALLOCATION_ORIG_AMOUNT,ALLOCATION_VALUE_DATE,ALLOCATION_TRX_DATE 
FROM	dbo.DEPOSIT_ALLOCATION		
WHERE	CODE = susp.SOURCE_REFF_CODE AND susp.SOURCE_REFF_NAME in ('DEPOSIT ALLOCATION', 'REVERSAL DEPOSIT ALLOCATION')
) dan
OUTER APPLY( 
SELECT	MOVE_REMARKS
FROM	dbo.DEPOSIT_MOVE			
WHERE	CODE = susp.SOURCE_REFF_CODE AND susp.SOURCE_REFF_NAME = 'DEPOSIT MOVE'
) dmv
OUTER APPLY( 
SELECT	RELEASE_REMARKS
FROM	dbo.DEPOSIT_RELEASE			
WHERE	CODE = susp.SOURCE_REFF_CODE AND susp.SOURCE_REFF_NAME = 'DEPOSIT RELEASE'
) drl
