BEGIN TRANSACTION 
USE IFINOPL
DECLARE  @1 NVARCHAR(50) = REPLACE('0004036/4/10/03/2025','/','.')
SELECT	AGREEMENT_ASSET.AGREEMENT_NO,AGREEMENT_ASSET.ASSET_NO,FIRST_PAYMENT_TYPE,BILLING_TYPE,HANDOVER_BAST_DATE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,dbo.AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO,INVOICE_STATUS,MATURITY_DATE
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.AGREEMENT_NO = AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO
JOIN	dbo.AGREEMENT_INFORMATION ON AGREEMENT_INFORMATION.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
LEFT JOIN	dbo.INVOICE ON INVOICE.INVOICE_NO = AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO
WHERE	AGREEMENT_ASSET.AGREEMENT_NO = @1

UPDATE	dbo.AGREEMENT_ASSET_AMORTIZATION 
SET		BILLING_DATE			= '2025-04-04'
		,mod_date				= getdate()	  
		,mod_by					= 'MTN_FAUZAN'		  
		,mod_ip_address			= 'IMON_2504000148' 
WHERE	AGREEMENT_NO = @1

SELECT	AGREEMENT_ASSET.AGREEMENT_NO,AGREEMENT_ASSET.ASSET_NO,FIRST_PAYMENT_TYPE,BILLING_TYPE,HANDOVER_BAST_DATE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,dbo.AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO,INVOICE_STATUS,MATURITY_DATE
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.AGREEMENT_NO = AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO
JOIN	dbo.AGREEMENT_INFORMATION ON AGREEMENT_INFORMATION.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
LEFT JOIN	dbo.INVOICE ON INVOICE.INVOICE_NO = AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO
WHERE	AGREEMENT_ASSET.AGREEMENT_NO = @1

    INSERT INTO MTN_DATA_DSF_LOG
    (   
        MAINTENANCE_NAME
        ,REMARK
        ,TABEL_UTAMA
        ,REFF_1
        ,REFF_2
        ,REFF_3
        ,CRE_DATE
        ,CRE_BY
    )
    VALUES
    (   
        'FZN_2504000148'
        ,'Detail Request: No Agreement: 0004036/4/10/03/2025 REVISI BILLING DATE SESUAI REQUEST LESSEE MENJADI TANGGAL 04/04/2025 Reason for the Request: dikarenakan saat ini di ifin masih tanggal 04/03/2025 Before: 04/03/2025 After: 04/04/2025'
        ,'AGREEMENT_ASSET_AMORTIZATION'
        ,'0004036/4/10/03/2025'
        ,null
        ,null
        ,GETDATE()
        ,'fauzan'
    );
ROLLBACK TRANSACTION 