BEGIN TRANSACTION 
DECLARE  @1 NVARCHAR(50) = REPLACE('0002586/4/10/07/2024','/','.')
		,@2 NVARCHAR(50) = REPLACE('0002587/4/10/07/2024','/','.')
SELECT	LEASE_ROUNDED_AMOUNT,BILLING_NO,AGREEMENT_ASSET.AGREEMENT_NO,AGREEMENT_ASSET.ASSET_NO,FIRST_PAYMENT_TYPE,BILLING_TYPE,HANDOVER_BAST_DATE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,dbo.AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO,INVOICE_STATUS,MATURITY_DATE,AGREEMENT_ASSET_AMORTIZATION.MOD_BY
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.AGREEMENT_NO = AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO
JOIN	dbo.AGREEMENT_INFORMATION ON AGREEMENT_INFORMATION.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
LEFT JOIN	dbo.INVOICE ON INVOICE.INVOICE_NO = AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO
WHERE	AGREEMENT_ASSET.AGREEMENT_NO in (@1,@2)
ORDER BY AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO, BILLING_NO ASC

UPDATE	AGREEMENT_ASSET_AMORTIZATION 
SET		DUE_DATE = '2025-05-31', BILLING_DATE = '2025-05-31', MOD_BY = 'MTN-FAUZAN', MOD_DATE = GETDATE(), MOD_IP_ADDRESS = 'imon-2504000023' 
WHERE	AGREEMENT_NO = REPLACE('0002586/4/10/07/2024','/','.') 
AND		BILLING_NO = 12
UPDATE	AGREEMENT_ASSET_AMORTIZATION 
SET		BILLING_AMOUNT = 2992500, MOD_BY = 'MTN-FAUZAN', MOD_DATE = GETDATE(), MOD_IP_ADDRESS = 'imon-2504000023' 
WHERE	AGREEMENT_NO = REPLACE('0002586/4/10/07/2024','/','.') 
AND		BILLING_NO = 13

UPDATE	AGREEMENT_ASSET_AMORTIZATION 
SET		DUE_DATE = '2025-05-31', BILLING_DATE = '2025-05-31', MOD_BY = 'MTN-FAUZAN', MOD_DATE = GETDATE(), MOD_IP_ADDRESS = 'imon-2504000023' 
WHERE	AGREEMENT_NO = REPLACE('0002587/4/10/07/2024','/','.')
AND		BILLING_NO = 12
UPDATE	AGREEMENT_ASSET_AMORTIZATION 
SET		BILLING_AMOUNT = 2992500, MOD_BY = 'MTN-FAUZAN', MOD_DATE = GETDATE(), MOD_IP_ADDRESS = 'imon-2504000023' 
WHERE	AGREEMENT_NO = REPLACE('0002587/4/10/07/2024','/','.')
AND		BILLING_NO = 13

SELECT	LEASE_ROUNDED_AMOUNT,BILLING_NO,AGREEMENT_ASSET.AGREEMENT_NO,AGREEMENT_ASSET.ASSET_NO,FIRST_PAYMENT_TYPE,BILLING_TYPE,HANDOVER_BAST_DATE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,dbo.AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO,INVOICE_STATUS,MATURITY_DATE,AGREEMENT_ASSET_AMORTIZATION.MOD_BY
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.AGREEMENT_NO = AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO
JOIN	dbo.AGREEMENT_INFORMATION ON AGREEMENT_INFORMATION.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
LEFT JOIN	dbo.INVOICE ON INVOICE.INVOICE_NO = AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO
WHERE	AGREEMENT_ASSET.AGREEMENT_NO in (@1,@2)
ORDER BY AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO, BILLING_NO ASC
ROLLBACK TRANSACTION 