BEGIN TRANSACTION 
USE IFINOPL
DECLARE  @1 NVARCHAR(50) = REPLACE('0002586/4/10/07/2024','/','.')
		,@2 NVARCHAR(50) = REPLACE('0000119/4/04/12/2021','/','.')
SELECT	ASSET_STATUS,BILLING_NO,AGREEMENT_ASSET.AGREEMENT_NO,AGREEMENT_ASSET.ASSET_NO,FIRST_PAYMENT_TYPE,BILLING_TYPE,HANDOVER_BAST_DATE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,dbo.AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO,INVOICE_STATUS,MATURITY_DATE
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
--JOIN dbo.AGREEMENT_MAIN ON AGREEMENT_MAIN.AGREEMENT_NO = AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.ASSET_NO = AGREEMENT_ASSET_AMORTIZATION.ASSET_NO
JOIN	dbo.AGREEMENT_INFORMATION ON AGREEMENT_INFORMATION.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
LEFT JOIN	dbo.INVOICE ON INVOICE.INVOICE_NO = AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO
WHERE	AGREEMENT_ASSET.AGREEMENT_NO = @2
AND ASSET_STATUS = 'RENTED'
ORDER BY AGREEMENT_ASSET_AMORTIZATION.ASSET_NO, BILLING_NO ASC

UPDATE dbo.AGREEMENT_ASSET_AMORTIZATION SET DUE_DATE = dateadd(MONTH,1,dateadd(day,-1,DUE_DATE)), BILLING_DATE = dateadd(MONTH,1,BILLING_DATE), BILLING_AMOUNT =  3900000  WHERE dbo.AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO = @2 AND BILLING_NO = 37  
UPDATE dbo.AGREEMENT_ASSET_AMORTIZATION SET DUE_DATE = dateadd(MONTH,1,dateadd(day,-1,DUE_DATE)), BILLING_DATE = dateadd(MONTH,1,dateadd(day,6,BILLING_DATE)), BILLING_AMOUNT =  3900000 WHERE dbo.AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO = @2 AND BILLING_NO >= 38  
UPDATE dbo.AGREEMENT_ASSET_AMORTIZATION SET DUE_DATE = '2025-07-14', BILLING_DATE = '2025-07-20', BILLING_AMOUNT =  125806 WHERE dbo.AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO = @2 AND BILLING_NO = 43  

SELECT	ASSET_STATUS,BILLING_NO,AGREEMENT_ASSET.AGREEMENT_NO,AGREEMENT_ASSET.ASSET_NO,FIRST_PAYMENT_TYPE,BILLING_TYPE,HANDOVER_BAST_DATE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,dbo.AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO,INVOICE_STATUS,MATURITY_DATE
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
--JOIN dbo.AGREEMENT_MAIN ON AGREEMENT_MAIN.AGREEMENT_NO = AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.ASSET_NO = AGREEMENT_ASSET_AMORTIZATION.ASSET_NO
JOIN	dbo.AGREEMENT_INFORMATION ON AGREEMENT_INFORMATION.AGREEMENT_NO = AGREEMENT_ASSET.AGREEMENT_NO
LEFT JOIN	dbo.INVOICE ON INVOICE.INVOICE_NO = AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO
WHERE	AGREEMENT_ASSET.AGREEMENT_NO = @2
AND ASSET_STATUS = 'RENTED'
ORDER BY AGREEMENT_ASSET_AMORTIZATION.ASSET_NO, BILLING_NO asc
ROLLBACK TRANSACTION 
