select		am.client_name 'CUSTOMER'
				,am.agreement_external_no 'PERJANJIAN_PELAKSANAAN'
				--,am.agreement_no 
				,inv.INVOICE_NO 'INVOICE_NO'
				,inv.DESCRIPTION 'PERIODE_SEWA'
				,inv.DUE_DATE 'JATUH_TEMPO'
				,am.AGREEMENT_DATE 'TANGGAL_PERJANJIAN_PELAKSANAAN'
				,inv.ASSET_TYPE_CODE 'JENIS_KENDARAAN'
				,inv.ASSET_NAME + '/' + inv.ASSET_YEAR 'MERK/TAHUN'
				,inv.FA_REFF_NO_03 'NO_RANGKA'
				,inv.FA_REFF_NO_02 'NO_MESIN'
				,inv.FA_REFF_NO_01 'NO_POLISI'
	from		agreement_main am
	OUTER APPLY(
				SELECT DISTINCT i.INVOICE_NO, id.DESCRIPTION, DUE_DATE, ASSET_TYPE_CODE, ASSET_NAME, FA_REFF_NO_03, FA_REFF_NO_02, FA_REFF_NO_01, ASSET_YEAR
				FROM dbo.invoice i 
				JOIN dbo.INVOICE_DETAIL id ON id.INVOICE_NO = i.INVOICE_NO 
				JOIN dbo.AGREEMENT_ASSET_AMORTIZATION ON AGREEMENT_ASSET_AMORTIZATION.INVOICE_NO = i.INVOICE_NO
				JOIN dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.ASSET_NO = AGREEMENT_ASSET_AMORTIZATION.ASSET_NO
				WHERE id.AGREEMENT_NO = am.AGREEMENT_NO) inv
	WHERE		am.CLIENT_NAME IN ('G4S SECURITY SERVICES', 'PUTRA MULIA TELECOMMUNICATION')
	ORDER BY	am.CLIENT_NAME, am.AGREEMENT_NO ASC
    


				--WHERE i.INVOICE_NO = '00001.DSF.INV.4.02.2022'