BEGIN TRANSACTION 
SELECT	FA_REFF_NO_01,HANDOVER_BAST_DATE,FIRST_PAYMENT_TYPE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,INVOICE_NO,* 
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.ASSET_NO = AGREEMENT_ASSET_AMORTIZATION.ASSET_NO WHERE AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO = (SELECT REPLACE('0003609/4/10/12/2024', '/', '.'))
UPDATE	AGREEMENT_ASSET 
SET		HANDOVER_BAST_DATE	= '2025-01-29' 
WHERE	ASSET_NO			= '2010.OPLAA.2412.000090'
UPDATE	dbo.AGREEMENT_ASSET_AMORTIZATION 
SET		DUE_DATE			= EOMONTH(DATEADD(MONTH,1, DUE_DATE))
		,BILLING_DATE		= EOMONTH(DATEADD(MONTH,1, DUE_DATE)) 
WHERE	ASSET_NO = '2010.OPLAA.2412.000090'
SELECT	FA_REFF_NO_01,HANDOVER_BAST_DATE,FIRST_PAYMENT_TYPE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,INVOICE_NO,* 
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.ASSET_NO = AGREEMENT_ASSET_AMORTIZATION.ASSET_NO WHERE AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO = (SELECT REPLACE('0003609/4/10/12/2024', '/', '.'))
ROLLBACK TRANSACTION 

BEGIN TRANSACTION 
SELECT	FA_REFF_NO_01,HANDOVER_BAST_DATE,FIRST_PAYMENT_TYPE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,INVOICE_NO,* 
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.ASSET_NO = AGREEMENT_ASSET_AMORTIZATION.ASSET_NO WHERE AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO = (SELECT REPLACE('0003631/4/10/12/2024', '/', '.')) AND FA_REFF_NO_01 = 'B9679PXA'
UPDATE	AGREEMENT_ASSET 
SET		HANDOVER_BAST_DATE	= '2025-01-29' 
WHERE	ASSET_NO			= '2010.OPLAA.2412.000180'
UPDATE	dbo.AGREEMENT_ASSET_AMORTIZATION
SET		DUE_DATE			= '2025-01-29'
		,BILLING_DATE		= '2025-01-29' 
WHERE	ASSET_NO = '2010.OPLAA.2412.000180' AND BILLING_NO = 1
UPDATE	dbo.AGREEMENT_ASSET_AMORTIZATION 
SET		DUE_DATE			= EOMONTH(DATEADD(MONTH,-2, DUE_DATE))
		,BILLING_DATE		= EOMONTH(DATEADD(MONTH,-2, DUE_DATE)) 
WHERE	ASSET_NO = '2010.OPLAA.2412.000180' AND BILLING_NO > 1
SELECT	FA_REFF_NO_01,HANDOVER_BAST_DATE,FIRST_PAYMENT_TYPE,DUE_DATE,BILLING_DATE,BILLING_AMOUNT,INVOICE_NO,* 
FROM	dbo.AGREEMENT_ASSET_AMORTIZATION 
JOIN	dbo.AGREEMENT_ASSET ON AGREEMENT_ASSET.ASSET_NO = AGREEMENT_ASSET_AMORTIZATION.ASSET_NO WHERE AGREEMENT_ASSET_AMORTIZATION.AGREEMENT_NO = (SELECT REPLACE('0003631/4/10/12/2024', '/', '.')) AND FA_REFF_NO_01 = 'B9679PXA'
ROLLBACK TRANSACTION 

